apiVersion: v1
kind: ConfigMap
metadata:
  name: kurl-helper-scripts
data:
  systemctl: |
    #!/bin/sh -x

    # override systemctl when using the restart command

    command=$1

    if [ "${command}-" == "restart-" ]; then

      # do stuff if restarting kubelet
      if [ "$2" == "kubelet" ]; then
        echo "restart kubelet"
        pkill -f kubelet

        source /var/lib/kubelet/kubeadm-flags.env
        KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf
        KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml

        # TODO - log files
        /usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS </dev/null &>/dev/null &
      fi
      exit 0
    fi

    # non-restart commands
    /usr/local/bin/systemctl_docker_replacement $@

  init.sh: |
    #/bin/sh -ex

    # Install dependencies for kURL which are missing in the base Ubuntu container

    apt-get update

    # get scripts for systemctl emulation
    apt-get install -y git
    git clone https://github.com/gdraheim/docker-systemctl-replacement.git
    cp docker-systemctl-replacement/files/docker/systemctl3.py /usr/local/bin/systemctl_docker_replacement

    # install other dependencies
    apt install -y \
        net-tools \
        curl \
        iproute2 \
        systemd \
        iptables \
        libnetfilter-conntrack3:amd64 \
        kmod \
        apt-transport-https \
        ca-certificates \
        curl \
        gnupg \
        lsb-release

    # Install just the docker CLI as described here: https://docs.docker.com/engine/install/ubuntu/
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo \
      "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update
    apt install -y docker-ce-cli
---
apiVersion: v1
kind: Pod
metadata:
    name: ubuntu-kurl
spec:
    containers:
    - name: kurl
      args:
      - -c
      - /root/init.sh; sleep 999999
      command:
      - /bin/sh
      image: ubuntu:18.04
      env:
      - name: DOCKER_HOST
        value: tcp://localhost:2375
      volumeMounts:
      - name: helper
        mountPath: /root/init.sh
        subPath: init.sh
      - name: systemctl
        mountPath: /usr/local/bin/systemctl
        subPath: systemctl
    - name: dind-daemon
      image: docker:dind
      env:
      - name: DOCKER_TLS_CERTDIR
        value: ""
      resources:
          requests:
              cpu: 20m
              memory: 512Mi
      securityContext:
          privileged: true
      volumeMounts:
        - name: docker-graph-storage
          mountPath: /var/lib/docker
    volumes:
      - name: docker-graph-storage
        emptyDir: {}
      - name: helper
        configMap:
          name: kurl-helper-scripts
          defaultMode: 0700
      - name: systemctl
        configMap:
          name: kurl-helper-scripts
          defaultMode: 0700
